name: 'Setup binstaller environment'
description: 'Set up common dependencies for binstaller workflows'

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Build binst
      shell: bash
      run: make build
