name: 'Setup binstaller environment'
description: 'Set up common dependencies for binstaller workflows'

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Set up Aqua
      uses: aquaproj/aqua-installer@d1fe50798dbadd4eb5b98957290ca175f6b4870f # v4.0.2
      with:
        aqua_version: v2.50.0

    - name: Build binst
      shell: bash
      run: make build