schema: v1
name: sigspy
repo: actionutils/sigspy
default_version: latest
asset:
    template: ${NAME}_${OS}_${ARCH}${EXT}
    default_extension: .tar.gz
    naming_convention:
        os: titlecase
        arch: lowercase
checksums:
    template: checksums.txt
    algorithm: sha256
unpack:
    strip_components: 0
