name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude') && github.event.comment.user.login == 'haya14busa') ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude') && github.event.comment.user.login == 'haya14busa') ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude') && github.event.review.user.login == 'haya14busa') ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')) && github.event.issue.user.login == 'haya14busa')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # This is an optional setting that allows Claude to read CI results on PRs
          additional_permissions: |
            actions: read
          
          # Use Claude Opus 4 for better code understanding and more autonomous operation
          model: "claude-opus-4-20250514"
          
          # Optional: Customize the trigger phrase (default: @claude)
          # trigger_phrase: "/claude"
          
          # Optional: Trigger when specific user is assigned to an issue
          # assignee_trigger: "claude-bot"
          
          # Allow Claude to run specific commands for binstaller project
          allowed_tools: |
            Bash(make:*)
            Bash(go:*)
            Bash(./binst)
            Bash(./binst:*)
            Bash(sh:*)
            Bash(bash:*)
            Bash(./install.sh)
            Bash(./installer.sh)
            Bash(git:*)
            Bash(ls:*)
            Bash(cd:*)
            Bash(pwd)
            Bash(cp:*)
            Bash(mv:*)
            Bash(rm:*)
            Bash(mkdir:*)
            Bash(touch:*)
            Bash(chmod:*)
            Bash(cat:*)
            Bash(head:*)
            Bash(tail:*)
            Bash(grep:*)
            Bash(sed:*)
            Bash(find:*)
            Bash(which:*)
            Bash(echo:*)
            Bash(tar:*)
            Bash(gzip:*)
            Bash(gunzip:*)
            Bash(curl:*)
            Bash(wget:*)
            Bash(diff:*)
            Bash(test:*)
            Bash(wc:*)
          
          # Optional: Custom environment variables for Claude
          # claude_env: |
          #   NODE_ENV: test

