name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-test:
    name: E2E Test
    runs-on: ${{ matrix.os }}
    permissions: {}  # Minimal permissions
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'


    - name: Install dependencies
      run: go mod download

    - name: Run E2E Tests
      run: go test -v ./e2etest
      env:
        # GITHUB_TOKEN is needed for goinstaller execution
        GITHUB_TOKEN: ${{ github.token }}
        # GH_TOKEN is needed for gh attestation verify in the generated installer script
        GH_TOKEN: ${{ github.token }}
