name: Test
on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
      with:
        egress-policy: audit

    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
      id: go

    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    - uses: denoland/setup-deno@v2
      with:
        deno-version: vx.x.x

    - uses: aquaproj/aqua-installer@d1fe50798dbadd4eb5b98957290ca175f6b4870f # v4.0.2
      with:
        aqua_version: v2.50.0

    - run: make setup

    - run: make ci

    - name: Generate test configs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: make test-gen-configs

    - name: Generate test installers
      run: make test-gen-installers

    - name: Test all supported platforms (reviewdog)
      run: make test-all-platforms

    - name: Generate files
      run: make gen

    - name: Fail if any diff exists
      run: test -z "$(git status -s)"

    - name: Test running generated installers
      run: make test-run-installers

    - name: Test aqua source
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: make test-aqua-source

    - name: Test check command
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "::group::Testing check command"
        make test-check
        echo "::endgroup::"
        
        # Test help output
        echo "::group::Check command help"
        ./binst check --help
        echo "::endgroup::"
