name: Test
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
      id: go

    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    - uses: denoland/setup-deno@v2
      with:
        deno-version: vx.x.x

    - run: make setup

    - uses: aquaproj/aqua-installer@5e54e5cee8a95ee2ce7c04cb993da6dfad13e59c # v3.1.2
      with:
        aqua_version: v2.50.0

    - run: make ci

    - name: Generate test configs
      run: make test-gen-configs

    - name: Generate test installers
      run: make test-gen-installers

    - name: Test all supported platforms (reviewdog)
      run: make test-all-platforms

    - name: Fail if any diff exists
      run: |
        if ! git diff; then
          echo "::error ::git diff detected - please commit the generated changes."
          exit 1
        fi

    - name: Test running generated installers
      run: make test-run-installers

    - name: Test aqua source
      run: make test-aqua-source
