name: Test
on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    name: CI Checks
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
      with:
        egress-policy: audit

    - uses: actions/checkout@v4

    - uses: ./.github/actions/setup

    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    - run: make setup

    - run: make ci

    - name: Fail if any diff exists
      run: |
        if [ -n "$(git status -s)" ]; then
          echo "::error::Uncommitted changes detected - please commit the generated changes."
          git status -s
          echo "::group::Diff of changes"
          git add -N .
          git diff
          echo "::endgroup::"
          exit 1
        fi

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: ci
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
      with:
        egress-policy: audit

    - uses: actions/checkout@v4

    - uses: ./.github/actions/setup

    - name: Run integration tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: make test-integration

    - name: Test help output
      run: |
        echo "::group::Comprehensive help"
        ./binst helpful
        echo "::endgroup::"

  platform-tests:
    name: Platform Tests
    runs-on: ubuntu-latest
    needs: ci
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
      with:
        egress-policy: audit

    - uses: actions/checkout@v4

    - uses: ./.github/actions/setup

    - name: Test all supported platforms (reviewdog)
      run: make test-all-platforms

  aqua-source-tests:
    name: Aqua Source Tests
    runs-on: ubuntu-latest
    needs: ci
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
      with:
        egress-policy: audit

    - uses: actions/checkout@v4

    - uses: ./.github/actions/setup

    - name: Test aqua source
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: make test-aqua-source