#!/bin/sh
# Code generated by binstaller. DO NOT EDIT.
#
set -e
usage() {
  this=$1
  cat <<EOF
$this: download ${NAME} from ${REPO}

Usage: $this [-b bindir] [-d] [-n] [tag]
  -b sets bindir or installation directory, Defaults to ${BINSTALLER_BIN:-${HOME}/.local/bin}
  -d turns on debug logging
  -n turns on dry run mode
   [tag] is a tag from
   https://github.com/charmbracelet/gum/releases
   If tag is missing, then the latest will be used.

 Generated by binstaller
  https://github.com/binary-install/binstaller
EOF
  exit 2
}

cat /dev/null <<EOF
------------------------------------------------------------------------
https://github.com/client9/shlib - portable posix shell functions
Public domain - http://unlicense.org
https://github.com/client9/shlib/blob/master/LICENSE.md
but credit (and pull requests) appreciated.
------------------------------------------------------------------------
EOF
is_command() {
  command -v "$1" >/dev/null
}
echoerr() {
  echo "$@" 1>&2
}
_logp=6
log_set_priority() {
  _logp="$1"
}
log_priority() {
  if test -z "$1"; then
    echo "$_logp"
    return
  fi
  [ "$1" -le "$_logp" ]
}
log_tag() {
  case $1 in
    0) echo "emerg" ;;
    1) echo "alert" ;;
    2) echo "crit" ;;
    3) echo "err" ;;
    4) echo "warning" ;;
    5) echo "notice" ;;
    6) echo "info" ;;
    7) echo "debug" ;;
    *) echo "$1" ;;
  esac
}
log_debug() {
  log_priority 7 || return 0
  echoerr "$(log_prefix)" "$(log_tag 7)" "$@"
}
log_info() {
  log_priority 6 || return 0
  echoerr "$(log_prefix)" "$(log_tag 6)" "$@"
}
log_err() {
  log_priority 3 || return 0
  echoerr "$(log_prefix)" "$(log_tag 3)" "$@"
}
log_crit() {
  log_priority 2 || return 0
  echoerr "$(log_prefix)" "$(log_tag 2)" "$@"
}
uname_os() {
  os=$(uname -s | tr '[:upper:]' '[:lower:]')
  case "$os" in
    msys*) os="windows" ;;
    mingw*) os="windows" ;;
    cygwin*) os="windows" ;;
  esac
  if [ "$os" = "sunos" ]; then
    if [ "$(uname -o)" = "illumos" ]; then
      os="illumos"
    else
      os="solaris"
    fi
  fi
  echo "$os"
}
uname_arch() {
  arch=$(uname -m)
  case $arch in
    x86_64) arch="amd64" ;;
    i86pc) arch="amd64" ;;
    x86) arch="386" ;;
    i686) arch="386" ;;
    i386) arch="386" ;;
    aarch64) arch="arm64" ;;
    armv5*) arch="armv5" ;;
    armv6*) arch="armv6" ;;
    armv7*) arch="armv7" ;;
  esac
  echo "${arch}"
}
uname_os_check() {
  os=$(uname_os)
  case "$os" in
    darwin) return 0 ;;
    dragonfly) return 0 ;;
    freebsd) return 0 ;;
    linux) return 0 ;;
    android) return 0 ;;
    midnightbsd) return 0 ;;
    nacl) return 0 ;;
    netbsd) return 0 ;;
    openbsd) return 0 ;;
    plan9) return 0 ;;
    solaris) return 0 ;;
    illumos) return 0 ;;
    windows) return 0 ;;
  esac
  log_crit "uname_os_check '$(uname -s)' got converted to '$os' which is not a GOOS value. Please file bug at https://github.com/client9/shlib"
  return 1
}
uname_arch_check() {
  arch=$(uname_arch)
  case "$arch" in
    386) return 0 ;;
    amd64) return 0 ;;
    arm64) return 0 ;;
    armv5) return 0 ;;
    armv6) return 0 ;;
    armv7) return 0 ;;
    ppc64) return 0 ;;
    ppc64le) return 0 ;;
    mips) return 0 ;;
    mipsle) return 0 ;;
    mips64) return 0 ;;
    mips64le) return 0 ;;
    s390x) return 0 ;;
    amd64p32) return 0 ;;
  esac
  log_crit "uname_arch_check '$(uname -m)' got converted to '$arch' which is not a GOARCH value.  Please file bug report at https://github.com/client9/shlib"
  return 1
}
cat /dev/null <<EOF
------------------------------------------------------------------------
End of functions from https://github.com/client9/shlib
------------------------------------------------------------------------
EOF


hash_sha256() {
  TARGET=${1:-/dev/stdin}
  if is_command gsha256sum; then
    hash=$(gsha256sum "$TARGET") || return 1
    echo "$hash" | cut -d ' ' -f 1
  elif is_command sha256sum; then
    hash=$(sha256sum "$TARGET") || return 1
    echo "$hash" | cut -d ' ' -f 1
  elif is_command shasum; then
    hash=$(shasum -a 256 "$TARGET" 2>/dev/null) || return 1
    echo "$hash" | cut -d ' ' -f 1
  elif is_command openssl; then
    hash=$(openssl dgst -sha256 "$TARGET") || return 1
    echo "$hash" | cut -d ' ' -f 2
  else
    log_crit "hash_sha256 unable to find command to compute sha-256 hash"
    return 1
  fi
}

hash_compute() {
  hash_sha256 "$1"
}


untar() {
  tarball=$1
  strip_components=${2:-0} # default 0
  case "${tarball}" in
  *.tar.gz | *.tgz) tar --no-same-owner -xzf "${tarball}" --strip-components "${strip_components}" ;;
  *.tar.xz) tar --no-same-owner -xJf "${tarball}" --strip-components "${strip_components}" ;;
  *.tar.bz2) tar --no-same-owner -xjf "${tarball}" --strip-components "${strip_components}" ;;
  *.tar) tar --no-same-owner -xf "${tarball}" --strip-components "${strip_components}" ;;
  *.gz) gunzip "${tarball}" ;;
  *.zip)
    # unzip doesn't have a standard --strip-components
    # Workaround: extract to a subdir and move contents up if stripping
    if [ "$strip_components" -gt 0 ]; then
      extract_dir=$(basename "${tarball%.zip}")_extracted
      unzip -q "${tarball}" -d "${extract_dir}"
      # Move contents of the *first* directory found inside extract_dir up
      # This assumes wrap_in_directory=true convention
      first_subdir=$(find "${extract_dir}" -mindepth 1 -maxdepth 1 -type d -print -quit)
      if [ -n "$first_subdir" ]; then
        # Move all contents (* includes hidden files)
        mv "${first_subdir}"/* .
        # Optionally remove the now-empty subdir and the extract_dir
        rmdir "${first_subdir}"
        rmdir "${extract_dir}"
      else
        log_warn "Could not find subdirectory in zip to strip components from ${extract_dir}"
        # Files are extracted in current dir anyway, proceed
      fi
    else
      unzip -q "${tarball}"
    fi
    ;;
  *)
    log_err "untar unknown archive format for ${tarball}"
    return 1
    ;;
  esac
}



hash_verify() {
  TARGET_PATH=$1
  SUMFILE=$2
  if [ -z "${SUMFILE}" ]; then
    log_err "hash_verify checksum file not specified in arg2"
    return 1
  fi
  got=$(hash_compute "$TARGET_PATH")
  if [ -z "${got}" ]; then
    log_err "failed to calculate hash: ${TARGET_PATH}"
    return 1
  fi

  BASENAME=${TARGET_PATH##*/}

  # Check for line matches in checksum file
  # Format: "<hash>  <filename>" or "<hash> *<filename>"
  # Filename may include path prefix (e.g., "deployment/m2/file.tar.gz")
  while IFS= read -r line; do
    # Normalize tabs to spaces
    line=$(echo "$line" | tr '\t' ' ')

    # Extract hash and filename parts
    # First field is the hash, rest is filename (which may contain spaces)
    line_hash=$(echo "$line" | cut -d' ' -f1)

    # Skip if hash doesn't match
    if [ "$line_hash" != "$got" ]; then
      continue
    fi

    # Hash matches, now check filename
    # Get everything after the hash and first space(s)
    # Skip the hash part (length of $got) plus at least one space
    hash_len=${#got}
    line_rest="${line#$got}"
    # Remove leading spaces
    while [ "${line_rest#[ ]}" != "$line_rest" ]; do
      line_rest="${line_rest#[ ]}"
    done

    # Remove leading asterisk if present (binary mode indicator)
    if [ "${line_rest#\*}" != "$line_rest" ]; then
      line_rest="${line_rest#\*}"
    fi

    # Extract just the filename without any path
    line_filename="${line_rest##*/}"

    # Check if the filename matches
    if [ "$line_filename" = "$BASENAME" ]; then
      return 0
    fi

    # Also check for hash-only line (no filename)
    if [ -z "$line_rest" ] || [ "$line_rest" = "$line_hash" ]; then
      return 0
    fi
  done < "$SUMFILE"

  log_err "hash_verify checksum for '$TARGET_PATH' did not verify"
  log_err "  Expected hash: ${got}"
  log_err "  Checksum file content:"
  cat "$SUMFILE" >&2
  return 1
}

# GitHub HTTP download functions with GITHUB_TOKEN support
github_http_download_curl() {
  local_file=$1
  source_url=$2
  header=$3
  if [ -n "$GITHUB_TOKEN" ]; then
    log_debug "Using GITHUB_TOKEN for authentication"
    if [ -z "$header" ]; then
      curl -fsSL -H "Authorization: Bearer $GITHUB_TOKEN" -o "$local_file" "$source_url"
    else
      curl -fsSL -H "Authorization: Bearer $GITHUB_TOKEN" -H "$header" -o "$local_file" "$source_url"
    fi
  else
    if [ -z "$header" ]; then
      curl -fsSL -o "$local_file" "$source_url"
    else
      curl -fsSL -H "$header" -o "$local_file" "$source_url"
    fi
  fi
}
github_http_download_wget() {
  local_file=$1
  source_url=$2
  header=$3
  if [ -n "$GITHUB_TOKEN" ]; then
    log_debug "Using GITHUB_TOKEN for authentication"
    if [ -z "$header" ]; then
      wget -q --header "Authorization: Bearer $GITHUB_TOKEN" -O "$local_file" "$source_url"
    else
      wget -q --header "Authorization: Bearer $GITHUB_TOKEN" --header "$header" -O "$local_file" "$source_url"
    fi
  else
    if [ -z "$header" ]; then
      wget -q -O "$local_file" "$source_url"
    else
      wget -q --header "$header" -O "$local_file" "$source_url"
    fi
  fi
}
github_http_download() {
  log_debug "github_http_download $2"
  if is_command curl; then
    github_http_download_curl "$@"
    return
  elif is_command wget; then
    github_http_download_wget "$@"
    return
  fi
  log_crit "github_http_download unable to find wget or curl"
  return 1
}
github_http_copy() {
  tmp=$(mktemp)
  github_http_download "${tmp}" "$@" || return 1
  body=$(cat "$tmp")
  rm -f "${tmp}"
  echo "$body"
}
github_release() {
  owner_repo=$1
  version=$2
  test -z "$version" && version="latest"
  giturl="https://github.com/${owner_repo}/releases/${version}"
  json=$(github_http_copy "$giturl" "Accept:application/json")
  test -z "$json" && return 1
  version=$(echo "$json" | tr -s '\n' ' ' | sed 's/.*"tag_name":"//' | sed 's/".*//')
  test -z "$version" && return 1
  echo "$version"
}

# --- Embedded Checksums (Format: VERSION:FILENAME:HASH) ---
EMBEDDED_CHECKSUMS="
0.15.0:gum_0.15.0_Darwin_arm64.tar.gz:82c5d460e5ba1366be26a890bb9275f5336c7fba403376ccc246aab5c19ed7ea
0.15.0:gum_0.15.0_Darwin_x86_64.tar.gz:cfb0817c7ef97adb703ecc946a150a2db8a3aa847c5896c2a3237014396c5f69
0.15.0:gum_0.15.0_Freebsd_arm64.tar.gz:d42c5c813d216feba9e19af3cbedc057b2c21ac7c469f779fc3e38983276500b
0.15.0:gum_0.15.0_Freebsd_armv6.tar.gz:90ea02b7e80e589c10233fdd444c04f62cae00c0366fbdc005fbcbf7641699fd
0.15.0:gum_0.15.0_Freebsd_armv7.tar.gz:b86bb294622078e1c47c688fdcb6c9cb2f43c939ad9172def16102e5166d2b69
0.15.0:gum_0.15.0_Freebsd_i386.tar.gz:d2c3755c1719c9bc26ef5b9ab30f4259c7dc7c38042d5db45e63739f8f963722
0.15.0:gum_0.15.0_Freebsd_x86_64.tar.gz:f7c1aad623d9dbcdad78ea17bf04785c09f6aaa1e013588ec0451a4c84aba3bd
0.15.0:gum_0.15.0_Linux_arm64.tar.gz:307bd78ee12e7265fa2971db6ebf9caf56cfec2f07cad66e044d400d7bcdc905
0.15.0:gum_0.15.0_Linux_armv6.tar.gz:68d2549a348349e83bebde8af93322824d22e986650a9c1128af595ccb6c92e3
0.15.0:gum_0.15.0_Linux_armv7.tar.gz:101e5c5ceafd04ee250720be29c4173cbc9f54390eecb1a6ceda2a39591c351e
0.15.0:gum_0.15.0_Linux_i386.tar.gz:64569a0938ba2a7bd2d98509ebcfb6374decabaa04b31ca9a81f90e2233e8ca5
0.15.0:gum_0.15.0_Linux_x86_64.tar.gz:97ead0ccab4320ac310bf6a3b6497dd48e583cba7d73fc723e7d0b4e94da6799
0.15.0:gum_0.15.0_Netbsd_arm64.tar.gz:4d103c68088289db2c94c4da427c6e20fb1a17201f4631b1084503c350e6a425
0.15.0:gum_0.15.0_Netbsd_armv6.tar.gz:34b46a8c58848d17f6aa72cd7a5c7f153ba9478355d7ebff1e0e46a4fe4529af
0.15.0:gum_0.15.0_Netbsd_armv7.tar.gz:39291e791e44a42cdcab85cde57c6433a8f0bbfd5a204f1b14daa354f3ba4a93
0.15.0:gum_0.15.0_Netbsd_i386.tar.gz:29268b7d1be30e5f1473da5b6d7414feb2b35517221576d962d43fe6df85ede6
0.15.0:gum_0.15.0_Netbsd_x86_64.tar.gz:5e29ac4a6d47fcae3773359282a954e01ab9db582cae9dd4ab0172003a256a99
0.15.0:gum_0.15.0_Openbsd_arm64.tar.gz:ffe134c3680f37c7200714b989342d217197c286458032981d7b32c544c8230c
0.15.0:gum_0.15.0_Openbsd_armv6.tar.gz:33b4bd736239caec9538feb7c1d2d9966b314af66a36d09ce27b36d6e34f9ac9
0.15.0:gum_0.15.0_Openbsd_armv7.tar.gz:3b068204c5b32dbc0e61c0a8b85c801b654d158c70f604b87de2ebe0316d9339
0.15.0:gum_0.15.0_Openbsd_i386.tar.gz:f1f91c3db8593d02d273026722bb5c97096a332ebb970295f8a6ee2790d2b7d3
0.15.0:gum_0.15.0_Openbsd_x86_64.tar.gz:e92ad1c0def6820d37050e6238c18d0107634a216749d523156b075b46d02d26
0.15.0:gum_0.15.0_Windows_i386.zip:ee330cd87e72297317c798bbb72bd6a619e02976526c40a6f19051250639a03d
0.15.0:gum_0.15.0_Windows_x86_64.zip:f7f62cb40823272269e693494a12082275d6adffe8ef30d92277da5895396c85
0.16.0:gum_0.16.0_Darwin_arm64.tar.gz:cc2b557f6b8a0966f15acf7e5bd5c2e1b76f049fa461d205b17927a74f11b283
0.16.0:gum_0.16.0_Darwin_x86_64.tar.gz:8009022b373768ff81d80f800cb051b461837bd9ccf7ddd4d42ea159732794d8
0.16.0:gum_0.16.0_Freebsd_arm64.tar.gz:a5d9f9443c18a1bb8bb7fa01389b0cef8e968962b600863f830eb702516f53da
0.16.0:gum_0.16.0_Freebsd_armv6.tar.gz:84aad8e0b346d3b94520f20a4fa763bb048f9ae8ee147d214587285a6aa27786
0.16.0:gum_0.16.0_Freebsd_armv7.tar.gz:3bb510506b6e12b28ed86657d935b371fe9f422898c220eceb51b6ed199b47c7
0.16.0:gum_0.16.0_Freebsd_i386.tar.gz:d63ad3705a66a98a2ea8ea822a4e2e76e3c970295e899299b6b7aaf115530f4c
0.16.0:gum_0.16.0_Freebsd_x86_64.tar.gz:63eb0ebd97acf4a734d5e550a1f474512e76b950724fab48fb3f6c8ca5b3919e
0.16.0:gum_0.16.0_Linux_arm64.tar.gz:c28e0a29b5da25df44b95e3f39c773bbb00b9583916431d5e7a762faf011bd0e
0.16.0:gum_0.16.0_Linux_armv6.tar.gz:a0208a129845457c77b0ad755546a94b16dd38f8f7181309e14ec91da59271f9
0.16.0:gum_0.16.0_Linux_armv7.tar.gz:2ab5da34ae54d459c2e119a4c4de7e3f5e47471d4ad4957e52b54d4289518da5
0.16.0:gum_0.16.0_Linux_i386.tar.gz:c2ad09fb568ce05f521a5f59a75c4c8c02bf4ea23f24a9482319b1a327f66561
0.16.0:gum_0.16.0_Linux_x86_64.tar.gz:7a403e5671bb0e00f93f7b6aa89ec46f7adbda6f7df5c7bad99a01826903b124
0.16.0:gum_0.16.0_Netbsd_arm64.tar.gz:52db6a1c3880032fbf680c307799ec96c6e5bc3c5d5c4215821ebe1e256eaece
0.16.0:gum_0.16.0_Netbsd_armv6.tar.gz:6a9f903e80196624b041315d98435643883e632a306d251365e3d3341e7f0781
0.16.0:gum_0.16.0_Netbsd_armv7.tar.gz:30680b9d44ec531a40a4f8da94178937a4a877612782d32f76f76d4d45da3dbe
0.16.0:gum_0.16.0_Netbsd_i386.tar.gz:b1da30530a2292a2d17ae4900ca06777e9c64a3004dd3cf315d45897acecaae3
0.16.0:gum_0.16.0_Netbsd_x86_64.tar.gz:0f8459d4fa2560b588cd7e2af0ecb843bfdb58fb8385e7af1975832b01efdbe5
0.16.0:gum_0.16.0_Openbsd_arm64.tar.gz:1ded43b72966b6dc2a80596811253d6f743ed35555cf69c1b0524c91f813e270
0.16.0:gum_0.16.0_Openbsd_armv6.tar.gz:bceb696aabaf91be3b5e24a9cd8e65ad9949b52c38a047e34552743b0e421d09
0.16.0:gum_0.16.0_Openbsd_armv7.tar.gz:21b14534965e097d140c327e920d3193a1e83c59ca487deae9993b900715d833
0.16.0:gum_0.16.0_Openbsd_i386.tar.gz:1e7a9fce7adbb996dc4e1c3ceaac8a778bf713c55256af25bed61ef0ed2a5ced
0.16.0:gum_0.16.0_Openbsd_x86_64.tar.gz:0bbc03148b90dee93f393863d986aa60474a83ba59a768c9ec9b74896ab86db1
0.16.0:gum_0.16.0_Windows_i386.zip:3730bae084056d5f985b30173a19c43e5878819d782baad1c65e0da216c461e1
0.16.0:gum_0.16.0_Windows_x86_64.zip:b9b4b38ba35ff47c572c4b55ddd0463e2ef3d574cb8701c29253ec64f5c370ed"

# Find embedded checksum for a given version and filename
find_embedded_checksum() {
  version="$1"
  filename="$2"
  echo "$EMBEDDED_CHECKSUMS" | grep -E "^${version}:${filename}:" | cut -d':' -f3
}
parse_args() {
  BINDIR="${BINSTALLER_BIN:-${HOME}/.local/bin}"
  DRY_RUN=0
  while getopts "b:dqh?xn" arg; do
    case "$arg" in
    b) BINDIR="$OPTARG" ;;
    d) log_set_priority 10 ;;
    q) log_set_priority 3 ;;
    h | \?) usage "$0" ;;
    x) set -x ;;
    n) DRY_RUN=1 ;;
    esac
  done
  shift $((OPTIND - 1))
  TAG="${1:-v0.16.0}"
}
tag_to_version() {
  if [ "$TAG" = "latest" ]; then
    log_info "checking GitHub for latest tag"
    REALTAG=$(github_release "${REPO}" "${TAG}") && true
    test -n "$REALTAG" || {
      log_crit "Could not determine latest tag for ${REPO}"
      exit 1
    }
  else
    # Assume TAG is a valid tag/version string
    REALTAG="$TAG"
  fi
  if test -z "$REALTAG"; then
    log_crit "unable to find '${TAG}' - use 'latest' or see https://github.com/${REPO}/releases for details"
    exit 1
  fi
  VERSION=${REALTAG#v} # Strip leading 'v'
  TAG="$REALTAG"       # Use the resolved tag
  log_info "Resolved version: ${VERSION} (tag: ${TAG})"
}



resolve_asset_filename() {

  # --- Apply Rules ---
  ASSET_FILENAME=""
  if [ "${UNAME_ARCH}" = 'amd64' ] && true
  then
    ARCH='x86_64'
  fi
  if [ "${UNAME_OS}" = 'darwin' ] && true
  then
    OS='Darwin'
  fi
  if [ "${UNAME_OS}" = 'linux' ] && true
  then
    OS='Linux'
  fi
  if [ "${UNAME_OS}" = 'windows' ] && true
  then
    OS='Windows'
  fi
  if [ "${UNAME_OS}" = 'windows' ] && true
  then
    EXT='.zip'
  fi
  if [ "${UNAME_ARCH}" = '386' ] && true
  then
    ARCH='i386'
  fi
  if [ "${UNAME_OS}" = 'freebsd' ] && true
  then
    OS='Freebsd'
  fi
  if [ "${UNAME_OS}" = 'netbsd' ] && true
  then
    OS='Netbsd'
  fi
  if [ "${UNAME_OS}" = 'openbsd' ] && true
  then
    OS='Openbsd'
  fi
  if [ -z "${ASSET_FILENAME}" ]; then
    ASSET_FILENAME="gum_${VERSION}_${OS}_${ARCH}${EXT}"
  fi
}
# Cleanup function to remove temporary files
cleanup() {
  if [ -n "$TMPDIR" ] && [ -d "$TMPDIR" ]; then
    log_debug "Cleaning up temporary directory: $TMPDIR"
    rm -rf -- "$TMPDIR"
  fi
}

execute() {
  STRIP_COMPONENTS=1
  CHECKSUM_FILENAME="checksums.txt"

  # --- Construct URLs ---
  GITHUB_DOWNLOAD="https://github.com/${REPO}/releases/download"
  ASSET_URL="${GITHUB_DOWNLOAD}/${TAG}/${ASSET_FILENAME}"
  CHECKSUM_URL=""
  if [ -n "$CHECKSUM_FILENAME" ]; then
    CHECKSUM_URL="${GITHUB_DOWNLOAD}/${TAG}/${CHECKSUM_FILENAME}"
  fi

  # --- Download and Verify ---
  TMPDIR=$(mktemp -d)
  trap 'rm -rf -- "$TMPDIR"' EXIT HUP INT TERM
  log_debug "Downloading files into ${TMPDIR}"
  log_info "Downloading ${ASSET_URL}"
  github_http_download "${TMPDIR}/${ASSET_FILENAME}" "${ASSET_URL}"

  # Try to find embedded checksum first
  EMBEDDED_HASH=$(find_embedded_checksum "$VERSION" "$ASSET_FILENAME")

  if [ -n "$EMBEDDED_HASH" ]; then
    log_info "Using embedded checksum for verification"

    # Verify using embedded hash
    got=$(hash_compute "${TMPDIR}/${ASSET_FILENAME}")
    if [ "$got" != "$EMBEDDED_HASH" ]; then
      log_crit "Checksum verification failed for ${ASSET_FILENAME}"
      log_crit "Expected: ${EMBEDDED_HASH}"
      log_crit "Got: ${got}"
      return 1
    fi
    log_info "Checksum verification successful"
  elif [ -n "$CHECKSUM_URL" ]; then
    # Fall back to downloading checksum file
    log_info "Downloading checksums from ${CHECKSUM_URL}"
    github_http_download "${TMPDIR}/${CHECKSUM_FILENAME}" "${CHECKSUM_URL}"
    log_info "Verifying checksum ..."
    hash_verify "${TMPDIR}/${ASSET_FILENAME}" "${TMPDIR}/${CHECKSUM_FILENAME}"
  else
    log_info "No checksum found, skipping verification."
  fi

  if [ -z "${EXT}" ] || [ "${EXT}" = ".exe" ]; then
    log_debug "Target is raw binary"
  else
    log_info "Extracting ${ASSET_FILENAME}..."
    (cd "${TMPDIR}" && untar "${ASSET_FILENAME}" "${STRIP_COMPONENTS}")
  fi
  BINARY_NAME='gum'
  if [ -z "${EXT}" ] || [ "${EXT}" = ".exe" ]; then
    BINARY_PATH="${TMPDIR}/${ASSET_FILENAME}"
  else
    BINARY_PATH="${TMPDIR}/gum"
  fi

  if [ "${UNAME_OS}" = "windows" ]; then
    case "${BINARY_NAME}" in *.exe) ;; *) BINARY_NAME="${BINARY_NAME}.exe" ;; esac
    case "${BINARY_PATH}" in *.exe) ;; *) BINARY_PATH="${BINARY_PATH}.exe" ;; esac
  fi

  if [ ! -f "${BINARY_PATH}" ]; then
    log_crit "Binary not found: ${BINARY_PATH}"
    log_crit "Listing contents of ${TMPDIR} ..."
    if command -v find >/dev/null 2>&1; then
      cd "${TMPDIR}" && find .
    else
      cd "${TMPDIR}" && ls -R .
    fi
    return 1
  fi
  # Install the binary
  INSTALL_PATH="${BINDIR}/${BINARY_NAME}"

  if [ "$DRY_RUN" = "1" ]; then
    log_info "[DRY RUN] ${BINARY_NAME} dry-run installation succeeded! (Would install to: ${INSTALL_PATH})"
  else
    log_info "Installing binary to ${INSTALL_PATH}"
    test ! -d "${BINDIR}" && install -d "${BINDIR}"
    install "${BINARY_PATH}" "${INSTALL_PATH}"
    log_info "${BINARY_NAME} installation complete!"
  fi
}

# --- Configuration  ---
NAME='gum'
REPO='charmbracelet/gum'
EXT='.tar.gz'

# use in logging routines
log_prefix() {
  echo "${REPO}"
}

parse_args "$@"

# --- Determine target platform ---
OS="${BINSTALLER_OS:-$(uname_os)}"
UNAME_OS="${OS}"

ARCH="${BINSTALLER_ARCH:-$(uname_arch)}"
UNAME_ARCH="${ARCH}"
log_info "Detected Platform: ${OS}/${ARCH}"

# --- Validate platform ---
uname_os_check "$OS"
uname_arch_check "$ARCH"

tag_to_version

resolve_asset_filename

execute
